name = "abi"
type = "javascript"
account_id = "a27a0f500bc67545f3a8deb2e45e4fa0"
workers_dev = true

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build:worker"
watch_dir = "build/index.js"

[build.upload]
format="service-worker"
